name: action_cable_plus
version: 1.0.1
description: >-
  ActionCable client for dart and flutter
homepage: https://github.com/namiwang/actioncable_dart
documentation: https://github.com/namiwang/actioncable_dart
environment:
  sdk: ">=2.12.0-0 <3.3.0"
dependencies:
  web_socket_channel: ^2.0.0
dev_dependencies:
  test:
